version: "3"
services:
  # Database
  db:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: snappyapp
      MYSQL_PASSWORD: "!snappyapp!"
      MYSQL_DATABASE: snappy
  # Database viewer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # api:
  #   container_name: audex
  #   build:
  #     context: ./Audex.API
  #     dockerfile: ./Audex.API/Dockerfile
  #   volumes:
  #     - ./LocorumBackend.API:/app/LocorumBackend.API
  #     - ./LocorumBackend.Models:/app/LocorumBackend.Models
  #   environment:
  #     - DOTNET_USE_POLLING_FILE_WATCHER=1
  #     - DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2
  #     - DOTNET_CLI_TELEMETRY_OPTOUT=1
  #     - AUDEX_DEVELOPMENT=1
  #   ports:
  #       - "5000:5000"
