# Generated by Django 3.2.9 on 2021-11-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_copy',
            field=models.TextField(default='dummy_message'),
            preserve_default=False,
        ),
    ]
