# Generated by Django 3.2.9 on 2021-11-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_sender_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_ID',
            new_name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(default='fake_user', on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='fake_sender', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_ID',
        ),
        migrations.DeleteModel(
            name='CHAT',
        ),
    ]
