# Generated by Django 3.2.9 on 2021-11-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_time']},
        ),
    ]
